services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0-beta
    container_name: bunkerweb
    ports:
      - 80:8080
      - 443:8443
    environment:
      API_WHITELIST_IP: 127.0.0.0/8 10.20.30.0/24
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.0-beta
    volumes:
      - bw-data:/data
    environment:
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: www.juiceshop.com bunkerweb.juiceshop.com
      MULTISITE: yes
      DISABLE_DEFAULT_SERVER: yes
      API_WHITELIST_IP: 127.0.0.0/8 10.20.30.0/24
      www.juiceshop.com_USE_REVERSE_PROXY: yes
      www.juiceshop.com_REVERSE_PROXY_URL: /
      www.juiceshop.com_REVERSE_PROXY_HOST: http://juice-shop:3000
      www.juiceshop.com_ALLOWED_METHODS: "GET|POST|PUT|DELETE"
      www.juiceshop.com_USE_BAD_BEHAVIOR: no
      bunkerweb.juiceshop.com_USE_UI: yes
      bunkerweb.juiceshop.com_USE_REVERSE_PROXY: yes
      bunkerweb.juiceshop.com_REVERSE_PROXY_URL: /
      bunkerweb.juiceshop.com_REVERSE_PROXY_HOST: http://bw-ui:7000
      bunkerweb.juiceshop.com_GENERATE_SELF_SIGNED_SSL: "yes"
      bunkerweb.juiceshop.com_MAX_CLIENT_SIZE: "50m"
      bunkerweb.juiceshop.com_ALLOWED_METHODS: "GET|POST|PUT|DELETE"
      bunkerweb.juiceshop.com_USE_BAD_BEHAVIOR: no
    restart: "unless-stopped"
    networks:
      - bw-universe

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.0-beta
    volumes:
      - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=Adm1nP4ssw0rd!
    restart: "unless-stopped"
    networks:
      - bw-universe

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    environment:
      NODE_ENV: production
      LOG_LEVEL: debug
    networks:
      - bw-services

  sql-injection:
    image: curlimages/curl:latest
    container_name: sql-injection
    depends_on:
      - juice-shop
    entrypoint: >
      sh -c "
        sleep 5 &&
        while true; do
          curl -X POST -d 'email=admin@juice-shop.com' -d 'password=\' OR \'1\'=\'1' http://www.juiceshop.com/rest/user/login;
          curl -X POST -d 'email=test@evil.com' -d 'password=\' OR \'x\'=\'x' http://www.juiceshop.com/rest/user/login;
          sleep 5;
        done
      "
    networks:
      - bw-services

  xss-attack:
    image: curlimages/curl:latest
    container_name: xss-attack
    depends_on:
      - juice-shop
    entrypoint: >
      sh -c "
        sleep 5 &&
        while true; do
          curl -X POST -d 'comment=<script>alert(\"XSS\")</script>' http://www.juiceshop.com/rest/product/1/reviews;
          curl -X POST -d 'comment=<img src=\"invalid-url\" onerror=\"alert(1)\">' http://www.juiceshop.com/rest/product/1/reviews;
          sleep 5;
        done
      "
    networks:
      - bw-services

  legitimate-traffic:
    image: curlimages/curl:latest
    container_name: legitimate-traffic
    depends_on:
      - juice-shop
    entrypoint: >
      sh -c "
        sleep 5 &&
        while true; do
          curl -X GET http://www.juiceshop.com;
          curl -X GET http://www.juiceshop.com/assets/public/css/styles.css;
          sleep 10;
        done
      "
    networks:
      - bw-services
      
volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services