version: "3.5"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0-beta
    container_name: bunkerweb
    ports:
      - 80:8080
      - 443:8443
    environment:
      API_WHITELIST_IP: 127.0.0.0/8 10.20.30.0/24
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.0-beta
    volumes:
      - bw-data:/data
    environment:
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: www.juiceshop.com bunkerweb.juiceshop.com
      MULTISITE: yes
      DISABLE_DEFAULT_SERVER: yes
      API_WHITELIST_IP: 127.0.0.0/8 10.20.30.0/24
      www.juiceshop.com_USE_REVERSE_PROXY: yes
      www.juiceshop.com_REVERSE_PROXY_URL: /
      www.juiceshop.com_REVERSE_PROXY_HOST: http://juice-shop:3000
      www.juiceshop.com_ALLOWED_METHODS: "GET|POST|PUT|DELETE"
      bunkerweb.juiceshop.com_USE_UI: yes
      bunkerweb.juiceshop.com_USE_REVERSE_PROXY: yes
      bunkerweb.juiceshop.com_REVERSE_PROXY_URL: /
      bunkerweb.juiceshop.com_REVERSE_PROXY_HOST: http://bw-ui:7000
      bunkerweb.juiceshop.com_GENERATE_SELF_SIGNED_SSL: "yes"
      bunkerweb.juiceshop.com_MAX_CLIENT_SIZE: "50m"
      bunkerweb.juiceshop.com_ALLOWED_METHODS: "GET|POST|PUT|DELETE"
    restart: "unless-stopped"
    networks:
      - bw-universe

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.0-beta
    volumes:
      - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=Adm1nP4ssw0rd!
    ports:
      - 7000:7000
    restart: "unless-stopped"
    networks:
      - bw-universe

  juice-shop:
    image: bkimminich/juice-shop
    networks:
      - bw-services

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
