{
 "title": "WAF Monitoring",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request number attack",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "hide": true,
       "id": "1",
       "type": "count"
      },
      {
       "field": "select field",
       "id": "3",
       "meta": {},
       "pipelineVariables": [
        { "name": "qps", "pipelineAgg": "1" }
       ],
       "settings": { "script": "params.qps*1000/$__interval_ms" },
       "type": "bucket_script"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Denied request per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Denied requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status:403",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Accepted requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "alias": "Accepted requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status: 200",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Today's Attack Every 1 minutes) ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URI TOP 10 Attack",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "transaction.request.uri.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IP TOP 10 Attack",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "client_ip.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " TOP 10 Attack  Message ",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "transaction.messages.message.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " TOP 10 Attack  Domain",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "transaction.request.headers.Host.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OWASP TOP 10 Rules ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "transaction.messages.details.ruleId.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Prevented Attacks Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "transaction.messages:*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}