filebeat.inputs:
  - type: log

    enabled: true

    paths:
      - /var/log/nginx/filebeat.vietcapitalbank.com.vn.access.log

    json.keys_under_root: true

    json.overwrite_keys: true

    json.add_error_key: true

filebeat.config.modules:
  path: ${path.config}/modules.d/\*.yml

  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

output.redis:
  hosts: ["redis:6379"]
  password: "gQr8qHroGX7gqj6Gf+AsFSaHhbjN2AJCKak3k34HX4l0/kR5"
  key: "grafana_logs"
  db: 0
  timeout: 5
